### ISSUE TITLE
Issues trying to install Dada2 from Test TS

### ISSUE THREAD

**Issue by yvanlebras** [bernt-matthias/mb-galaxy-tools#4]
Dear Wonder Matthias,

I just discover your amazing work on dada2. It seems that this tool suite is of first interest for people working on amplicon sequencing. Trying the installation of the tool suite, I encounter issues and installation didn't succeed. Maybe this is "just" due to the fact that dev is not finish ?

**Comment by bernt-matthias** [comment]
I'm just updating the tools in the TTS. So you might try again. Would be great to have some feedback or review before I try to put them to the TS. 

What exactly was the problem. I also experienced a problem with conda (https://github.com/bioconda/bioconda-recipes/issues/13846#issuecomment-485841543) which I could only solve by upgrading conda.

**Comment by bernt-matthias** [comment]
Just have seen this https://benjjneb.github.io/dada2/ReleaseNotes_1_12.html .. but not yet in conda

**Comment by bernt-matthias** [comment]
I also have problems installing.. somehow I needed to choose "install" from the repository actions for each tool. No idea what's going on there.

**Comment by yvanlebras** [comment]
I just discover I had an issue on the file system, and I suppose this was my problem... I am trying a new installation of the dada2 suite just now and keep you infiormed! Thank you for your help

**Comment by yvanlebras** [comment]
Ok, Installation ok. But needed to reinstall conda dependencies from the admin Galaxy panel... don't know why, but maybe because I installed from the tool suite as you mentionned.

Now, I am testing tools, and it seems that paired-end datasets can be available """only""" from data collection. Is it something better you think or we can also enable the use of paired-end "single" datasets ?

**Comment by bernt-matthias** [comment]
> Now, I am testing tools, and it seems that paired-end datasets can be available """only""" from data collection. Is it something better you think or we can also enable the use of paired-end "single" datasets ?

This affects only filterAndTrim, right? So far I mainly thought about the case of a multi sample analysis... We could allow this by `<param ... multiple="true">` or by extending the conditional. I guess the former is keeps the form simpler. 

One Problem is that the tool `dada2: sequence counts` needs the identifiers of the collection elements to track the samples through the different steps.

**Comment by bernt-matthias** [comment]
I was also trying on our Galaxy, seems that all but the data_manager works. Is the manager working for you?

**Comment by bernt-matthias** [comment]
Was quite late when I answered your previous questions. Now I understood that you suggested to give forward and reverse reads in separate input fields. I have implemented this now (in filterAndTrim).

**Comment by bernt-matthias** [comment]
Dadamanager (lol) should work now. have updated it in the TTS.

**Comment by bernt-matthias** [comment]
Hi @yvanlebras . Did you have time to look into the tools? I think they are ready for the TS. But before I push them I would really like to know if they connect nicely to downstream tools or if the output (format) should be improved (or other formats be added)?

**Comment by yvanlebras** [comment]
Hi Bernt! I will give a try in the 10 next days if it's ok for you

**Comment by bernt-matthias** [comment]
Sure.

**Comment by yvanlebras** [comment]
Apparently there is an issue with [dada2_plotqualityprofile]( https://testtoolshed.g2.bx.psu.edu/repository?repository_id=59705904f206ac02 ). Maybe due to the update to try using paired datasets who are not on a collection ?
The problem is that when selecting "paired - non batch", the tool didn't find any dataset collection. If I select "paired - batch", it's ok....

**Comment by yvanlebras** [comment]
... and executing the same tool but on single dataset (single end), I have an issue regarding ldpaths dependency access
```
Fatal error: Exit code 2 ()
/export/tool_deps/_conda/envs/__bioconductor-dada2@1.10.0/bin/R: 238: .: Can't open /export/tool_deps/_conda/envs/__bioconductor-dada2@1.10.0/lib/R/etc/ldpaths
/export/tool_deps/_conda/envs/__bioconductor-dada2@1.10.0/lib/R/bin/R: 238: .: Can't open /export/tool_deps/_conda/envs/__bioconductor-dada2@1.10.0/lib/R/etc/ldpaths
```

**Comment by bernt-matthias** [comment]
> Apparently there is an issue with [dada2_plotqualityprofile](https://testtoolshed.g2.bx.psu.edu/repository?repository_id=59705904f206ac02). Maybe due to the update to try using paired datasets who are not on a collection ?
> The problem is that when selecting "paired - non batch", the tool didn't find any dataset collection. If I select "paired - batch", it's ok....

I think I did not change this tool yet to allow for alowing one/more pairs as input. I will try to change this here as well. Is the help specific enough to understand the difference between batch and non-batch -- in particular in combination with the `Aggregate data` boolean input?

The second problem seems to be a conda/bioconda issue. The suggestion from the bioconda gitter was to "force reinstall r-base==3.5.1" into the environment. 

Could you send me the conda-meta/history file of the dada2 environment.

**Comment by yvanlebras** [comment]
Thank you for your rapid answer.

Concerning first issue, thank you to try modifying it and maybe give the possibility to use paired data outside of a data collection. True that it's quite difficult to fully understand the differences between batch/non-batch and "aggregate data", and maybe a picture on the tool help section will help. But I think this is ok for now, and if users don't understand on a first approach, re-executing the tool changing these parameters will for sure help to understand differences between several pdf files and several plot inside pdf file(s) ;)

Content of my ~/tool_deps/_conda/envs/__bioconductor-dada2@1.10.0/conda-meta/history file:

```
==> 2019-05-06 15:14:29 <==
# cmd: /export/tool_deps/_conda/bin/conda create -y --override-channels --channel iuc --channel bioconda --channel conda-forge --channel defaults --na$
+bioconda::bioconductor-biobase-2.42.0-r351h14c3975_1
+bioconda::bioconductor-biocgenerics-0.28.0-r351_1
+bioconda::bioconductor-biocparallel-1.16.6-r351h1c2f66e_0
+bioconda::bioconductor-biostrings-2.50.2-r351h14c3975_0
+bioconda::bioconductor-dada2-1.10.0-r351hf484d3e_0
+bioconda::bioconductor-delayedarray-0.8.0-r351h14c3975_0
+bioconda::bioconductor-genomeinfodb-1.18.1-r351_0
+bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
+bioconda::bioconductor-genomicalignments-1.18.1-r351h14c3975_0
+bioconda::bioconductor-genomicranges-1.34.0-r351h14c3975_0
+bioconda::bioconductor-iranges-2.16.0-r351h14c3975_0
+bioconda::bioconductor-rsamtools-1.34.0-r351hf484d3e_0
+bioconda::bioconductor-s4vectors-0.20.1-r351h14c3975_0
+bioconda::bioconductor-shortread-1.40.0-r351hf484d3e_0
+bioconda::bioconductor-summarizedexperiment-1.12.0-r351_0
+bioconda::bioconductor-xvector-0.22.0-r351h14c3975_0
+bioconda::bioconductor-zlibbioc-1.28.0-r351h14c3975_0
+bioconda::r-data.table-1.11.6-r351hc070d10_0
+conda-forge::bzip2-1.0.6-h14c3975_1002
+conda-forge::ca-certificates-2019.3.9-hecc5488_0
+conda-forge::cairo-1.16.0-ha4e643d_1000
+conda-forge::curl-7.64.1-hf8cf82a_0
+conda-forge::fontconfig-2.13.1-he4413a7_1000
+conda-forge::freetype-2.10.0-he983fc9_0
+conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_1
+conda-forge::gcc_linux-64-7.3.0-h553295d_3
+conda-forge::gettext-0.19.8.1-hc5be6a0_1002
+conda-forge::gcc_linux-64-7.3.0-h553295d_3
+conda-forge::gettext-0.19.8.1-hc5be6a0_1002
+conda-forge::glib-2.58.3-hf63aee3_1001
+conda-forge::graphite2-1.3.13-hf484d3e_1000
+conda-forge::gsl-2.4-h294904e_1006
+conda-forge::gxx_impl_linux-64-7.3.0-hdf63c60_1
+conda-forge::gxx_linux-64-7.3.0-h553295d_3
+conda-forge::harfbuzz-2.4.0-h37c48d4_0
+conda-forge::icu-58.2-hf484d3e_1000
+conda-forge::jpeg-9c-h14c3975_1001
+conda-forge::krb5-1.16.3-h05b26f9_1001
+conda-forge::libblas-3.8.0-8_openblas
+conda-forge::libcblas-3.8.0-8_openblas
+conda-forge::libcurl-7.64.1-hda55be3_0
+conda-forge::libedit-3.1.20170329-hf8c457e_1001
+conda-forge::libffi-3.2.1-he1b5a44_1006
+conda-forge::libiconv-1.15-h516909a_1005
+conda-forge::libidn2-2.1.1-h14c3975_0
+conda-forge::libpng-1.6.37-hed695b0_0
+conda-forge::libssh2-1.8.2-h22169c7_2
+conda-forge::libtiff-4.0.10-h648cc4a_1001
+conda-forge::libunistring-0.9.10-h14c3975_0
+conda-forge::libuuid-2.32.1-h14c3975_1000
+conda-forge::libxcb-1.13-h14c3975_1002
+conda-forge::libxml2-2.9.9-h13577e0_0
+conda-forge::make-4.2.1-h14c3975_2004
+conda-forge::ncurses-6.1-hf484d3e_1002
+conda-forge::openblas-0.3.6-h6e990d7_1
+conda-forge::openssl-1.1.1b-h14c3975_1
+conda-forge::openblas-0.3.6-h6e990d7_1
+conda-forge::openssl-1.1.1b-h14c3975_1
+conda-forge::pango-1.40.14-h4ea9474_1004
+conda-forge::pcre-8.41-hf484d3e_1003
+conda-forge::pixman-0.34.0-h14c3975_1003
+conda-forge::pthread-stubs-0.4-h14c3975_1001
+conda-forge::r-assertthat-0.2.1-r351h6115d3f_0
+conda-forge::r-base-3.5.1-h271c98b_1006
+conda-forge::r-bh-1.69.0_1-r351h6115d3f_0
+conda-forge::r-bitops-1.0_6-r351h96ca727_1002
+conda-forge::r-cli-1.1.0-r351h6115d3f_0
+conda-forge::r-colorspace-1.4_1-r351hcdcec82_0
+conda-forge::r-crayon-1.3.4-r351h6115d3f_1001
+conda-forge::r-digest-0.6.18-r351h96ca727_1000
+conda-forge::r-fansi-0.4.0-r351h96ca727_1000
+conda-forge::r-formatr-1.6-r351h6115d3f_0
+conda-forge::r-futile.logger-1.4.3-r351h6115d3f_1001
+conda-forge::r-futile.options-1.0.1-r351h6115d3f_1000
+conda-forge::r-ggplot2-3.1.1-r351h6115d3f_0
+conda-forge::r-glue-1.3.1-r351hcdcec82_0
+conda-forge::r-gtable-0.3.0-r351h6115d3f_0
+conda-forge::r-hwriter-1.3.2-r351h6115d3f_1001
+conda-forge::r-labeling-0.3-r351h6115d3f_1001
+conda-forge::r-lambda.r-1.2.3-r351h6115d3f_1000
+conda-forge::r-lattice-0.20_38-r351h96ca727_1000
+conda-forge::r-latticeextra-0.6_28-r351h6115d3f_1001
+conda-forge::r-lazyeval-0.2.2-r351hcdcec82_0
+conda-forge::r-magrittr-1.5-r351h6115d3f_1001
+conda-forge::r-mass-7.3_51.4-r351hcdcec82_0
+conda-forge::r-magrittr-1.5-r351h6115d3f_1001
+conda-forge::r-mass-7.3_51.4-r351hcdcec82_0
+conda-forge::r-matrix-1.2_17-r351hcdcec82_0
+conda-forge::r-matrixstats-0.54.0-r351h96ca727_1000
+conda-forge::r-mgcv-1.8_28-r351hcdcec82_0
+conda-forge::r-munsell-0.5.0-r351h6115d3f_1001
+conda-forge::r-nlme-3.1_139-r351h9bbef5b_0
+conda-forge::r-pillar-1.3.1-r351h6115d3f_1000
+conda-forge::r-pkgconfig-2.0.2-r351h6115d3f_1001
+conda-forge::r-plyr-1.8.4-r351h29659fb_1002
+conda-forge::r-r6-2.4.0-r351h6115d3f_0
+conda-forge::r-rcolorbrewer-1.1_2-r351h6115d3f_1001
+conda-forge::r-rcpp-1.0.1-r351h0357c0b_0
+conda-forge::r-rcppparallel-4.4.2-r351h0357c0b_0
+conda-forge::r-rcurl-1.95_4.12-r351hcdcec82_0
+conda-forge::r-reshape2-1.4.3-r351h29659fb_1003
+conda-forge::r-rlang-0.3.4-r351hcdcec82_0
+conda-forge::r-scales-1.0.0-r351h29659fb_1001
+conda-forge::r-snow-0.4_3-r351h6115d3f_1000
+conda-forge::r-stringi-1.4.3-r351h0357c0b_0
+conda-forge::r-stringr-1.4.0-r351h6115d3f_0
+conda-forge::r-tibble-2.1.1-r351hcdcec82_0
+conda-forge::r-utf8-1.1.4-r351h96ca727_1000
+conda-forge::r-viridislite-0.3.0-r351h6115d3f_1001
+conda-forge::r-withr-2.1.2-r351h6115d3f_1000
+conda-forge::readline-7.0-hf8c457e_1001
+conda-forge::tk-8.6.9-h84994c4_1001
+conda-forge::wget-1.20.1-h90d6eec_0
+conda-forge::xorg-kbproto-1.0.7-h14c3975_1002
+conda-forge::wget-1.20.1-h90d6eec_0
+conda-forge::xorg-kbproto-1.0.7-h14c3975_1002
+conda-forge::xorg-libice-1.0.9-h516909a_1004
+conda-forge::xorg-libsm-1.2.3-h84519dc_1000
+conda-forge::xorg-libx11-1.6.7-h14c3975_1000
+conda-forge::xorg-libxau-1.0.9-h14c3975_0
+conda-forge::xorg-libxdmcp-1.1.3-h516909a_0
+conda-forge::xorg-libxext-1.3.4-h516909a_0
+conda-forge::xorg-libxrender-0.9.10-h516909a_1002
+conda-forge::xorg-renderproto-0.11.1-h14c3975_1002
+conda-forge::xorg-xextproto-7.3.0-h14c3975_1002
+conda-forge::xorg-xproto-7.0.31-h14c3975_1007
+conda-forge::xz-5.2.4-h14c3975_1001
+conda-forge::zlib-1.2.11-h14c3975_1004
+defaults::_r-mutex-1.0.0-anacondar_1
+defaults::binutils_impl_linux-64-2.31.1-h6176602_1
+defaults::binutils_linux-64-2.31.1-h6176602_3
+defaults::bwidget-1.9.11-1
+defaults::gfortran_impl_linux-64-7.3.0-hdf63c60_1
+defaults::gfortran_linux-64-7.3.0-h553295d_3
+defaults::libgcc-ng-8.2.0-hdf63c60_1
+defaults::libgfortran-ng-7.3.0-hdf63c60_0
+defaults::libstdcxx-ng-8.2.0-hdf63c60_1
+defaults::tktable-2.10-h14c3975_0
# create specs: bioconductor-dada2 1.10.0*
```

**Comment by yvanlebras** [comment]
I endly succeed to force reinstallation of R on the conda env... And can continue testing.. Thank you so much!

**Comment by bernt-matthias** [comment]
Regarding dada2_plotqualityprofile: 
- do you have a list:paired collection? Or just a pair? This should actually work. 
- do you think we should allow the input the paired data as separate files here as well?

**Comment by yvanlebras** [comment]
I have both a list:paired collection and two separate files for a pair. Using the a list:paired collection, the collection doesn't appears on the "short read data" space if I choose "paired - non batch", only appears when I select "paired - batch"... don't know why...
YEs I think it's better to have the possibility to use the tool on paired data as separate files as it seems to me sometimes users can have issues with collections...

**Comment by bernt-matthias** [comment]
> I have both a list:paired collection and two separate files for a pair. Using the a list:paired collection, the collection doesn't appears on the "short read data" space if I choose "paired - non batch", only appears when I select "paired - batch"... don't know why...

Odd this param `<param argument="fl" type="data_collection" collection_type="list:paired" format="fastqsanger,fastqsanger.gz" label="Short read data"/>` should then actually work. Also tested it here. The datatype is probably also correctly set for your data sets?

> YEs I think it's better to have the possibility to use the tool on paired data as separate files as it seems to me sometimes users can have issues with collections...

OK. Will do. Even if I'm always a bit afraid that the correct data sets are paired in the calculations.

**Comment by yvanlebras** [comment]
Just to be sure we are speaking about the same issue ;)

![image](https://user-images.githubusercontent.com/7910679/58185791-061c8280-7cb4-11e9-8dee-1dff7df7a5c6.png)

Here you can see the tool is not finding my collection but I have a collection of paired data in fastqsanger format...

![image](https://user-images.githubusercontent.com/7910679/58185979-4e3ba500-7cb4-11e9-8792-82b483d57f1b.png)

And here, it's ok....

**Comment by bernt-matthias** [comment]
OK. Dataset 27 is only a single pair. paired-nonbatch only accepts a list of pairs. Actually this might be acceptable since for a single pair there is no difference between batch/non batch -- or?

**Comment by yvanlebras** [comment]
![image](https://user-images.githubusercontent.com/7910679/58186410-200a9500-7cb5-11e9-82ed-6faf724046dd.png)
 ok, I see.. You're right... ITM, I found strange to have the possibility to execute a tool ""only"" on a list of pairs and not on such a list if there is only one pair.... No ?


Another question with filterandtrim, how can we give a orient.fw AND a orient.rv ? Note that there is a typo on the `String present at the start of valid reads` parameter help as it indicates "orinent.fwd".

**Comment by bernt-matthias** [comment]
> Another question with filterandtrim, how can we give a orient.fw AND a orient.rv ? 

According to the documentation there is no `orient.rv` parameter.

**Comment by yvanlebras** [comment]
hmm you're right... I was seeing people dealing with some orient.rev things but I think it was in a preprocess step to give it to dada2 and then process all primers (fw and reverse) through the orient.fwd parameter. Sorry for that mistake... 
I have to try deeper how to deal with that into Galaxy and go back to you.

**Comment by bernt-matthias** [comment]
Just made some updates: https://github.com/bernt-matthias/mb-galaxy-tools/pull/5/commits/a54770771e567c7ad8a9dd75cc4689c3935ef11c

**Comment by bernt-matthias** [comment]
dada2 is "now" at IUC https://github.com/galaxyproject/tools-iuc/pull/2483

closing this here
